# Generated by Django 4.2 on 2023-04-28 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
