# Generated by Django 4.2 on 2023-04-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visited',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
