# Generated by Django 4.2 on 2023-04-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_visited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='visited',
            new_name='watcher',
        ),
    ]
