# Generated by Django 4.2 on 2023-04-25 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
