# Generated by Django 4.2 on 2023-04-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
    ]
