# Generated by Django 4.2 on 2023-04-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_image_image_alter_image_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(blank=True, max_length=500, null=True, related_name='posts_images', to='posts.image'),
        ),
    ]
