# Generated by Django 4.2 on 2023-04-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_remove_post_image_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
