# Generated by Django 4.2 on 2023-04-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_likes'),
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='post',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='post',
            field=models.ManyToManyField(related_name='bookmarks', to='posts.post'),
        ),
    ]
