# Generated by Django 4.2 on 2023-05-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='mark',
            field=models.BooleanField(default=False),
        ),
    ]
