# Generated by Django 4.2 on 2023-04-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_reigondepth3_alter_address_reigondepth1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitiude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
