# Generated by Django 4.2 on 2023-04-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_address_latitiude_remove_address_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='reigonDepth1',
            new_name='regionDepth1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='reigonDepth2',
            new_name='regionDepth2',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='reigonDepth3',
            new_name='regionDepth3',
        ),
    ]
