version: '3'

services:
  
  web:
    image: elk:7.14.0
    container_name: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command:  gunicorn --bind 0.0.0.0:8000 config.wsgi:application 
    restart: always
    volumes:
      - .:/code
      # - logs_volume:/code/app/logs
      - static_volume:/code/app/static
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - petmo

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    volumes:
      - .docker/nginx/conf.d/:/etc/nginx/conf.d
      - static_volume:/home/app/static
    ports:
      - 80:80
    depends_on:
      - web 
    networks:
      - petmo
  
volumes:
  static_volume:
  # logs_volume:

networks:
  petmo:
    driver: bridge    