# Generated by Django 4.2 on 2023-05-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalTypes', models.CharField(choices=[('고양이', '고양이'), ('강아지', '강아지'), ('물고기', '물고기'), ('햄스터', '햄스터'), ('파충류', '파충류'), ('토끼', '토끼'), ('기타', '기타')], max_length=255)),
            ],
        ),
    ]
