# Generated by Django 4.2 on 2023-04-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('fish', 'fish'), ('hamster', 'hamster'), ('reptile', 'reptile'), ('rabbit', 'rabbit'), ('other', 'other')], max_length=255)),
            ],
        ),
    ]
