# Generated by Django 4.2 on 2023-04-16 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ManyToManyField(related_name='user_pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
