# Generated by Django 4.2 on 2023-05-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animalTypes',
            field=models.CharField(choices=[('고양이', '고양이'), ('강아지', '강아지'), ('물고기', '물고기'), ('햄스터', '햄스터'), ('파충류', '파충류'), ('토끼', '토끼'), ('새', '새'), ('기타', '기타')], max_length=255),
        ),
    ]
