# Generated by Django 4.2 on 2023-04-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_remove_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('fish', 'fish'), ('hamster', 'hamster'), ('reptile', 'reptile'), ('rabbit', 'rabbit'), ('other', 'other')], max_length=255),
        ),
    ]
