# Generated by Django 4.2 on 2023-04-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0005_alter_commentlike_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
